### ISSUE TITLE
Problems in Jenkins when there is no TTY attached

### ISSUE THREAD

**Issue by goloroden** [pgilad/grunt-dev-update#21]
You are using the inquirer module, which in turn uses the ttys module.

This module throws an exception when `/dev/tty` could not be opened. inquirer 0.8.1, in turn, now [relies on ttys](https://github.com/SBoudrias/Inquirer.js/commit/b666d2a2f0d42b8f1987b9b9efd3476d96517598).

This causes Grunt to crash when grunt-dev-update is used on a server without TTY, e.g. a Jenkins build server. The problem is that grunt-dev-update [always loads inquirer](https://github.com/pgilad/grunt-dev-update/blob/e2f18a8b50a60a440e6f3639b7321750d90b7b34/tasks/lib/dev_update.js#L9), even if it is not being used because it's configured for [report mode](https://github.com/pgilad/grunt-dev-update/blob/e2f18a8b50a60a440e6f3639b7321750d90b7b34/tasks/lib/dev_update.js#L153-L155) or [force mode](https://github.com/pgilad/grunt-dev-update/blob/e2f18a8b50a60a440e6f3639b7321750d90b7b34/tasks/lib/dev_update.js#L166-L169).

This should be fixed, otherwise grunt-dev-update is not usable on a build server :-(

The easiest solution would be to load inquirer [only when needed](https://github.com/pgilad/grunt-dev-update/blob/e2f18a8b50a60a440e6f3639b7321750d90b7b34/tasks/lib/dev_update.js#L172-L183). This is not as nice as having all `require` calls on top, but it should solve this issue.

**Comment by pgilad** [comment]
Yep I agree, inline loading would be a valid solution here. Thanks!
