### ISSUE TITLE
When new packages are available, devUpdate stops with error

### ISSUE THREAD

**Issue by philwareham** [pgilad/grunt-dev-update#26]
grunt-dev-update v2.0.0

I have the option configured:

    updateType: 'report'

And yet, whenever a package is out-of-date my grunt build errors and stops at devUpdate check. Worked fine in v1.x so not sure what's wrong here.

**Comment by erredeco** [comment]
I get a similar problem; but I have `updateType: 'prompt'` ; launching it breaks with a message:

Fatal error: Task failed due to Error

**Comment by pgilad** [comment]
Hopefully fixed with https://github.com/pgilad/grunt-dev-update/commit/3d0e747929dcf2e303f28a71756a90c19c9d7342
