### ISSUE TITLE
error with node@6

### ISSUE THREAD

**Issue by diggy** [pgilad/grunt-dev-update#27]
with `--verbose` flag:

````
Found 0 dependencies to check for latest version
Error
Fatal error: Task failed due to Error
````

This happened after upgrading from `node@5` to `node@6`. Upping to `grunt-dev-update@^2.0.0` did not help.

System info

````
os: macOS Sierra 10.12.3 (16D32)
node: v6.10.0
npm: 4.1.2
````

**Comment by pgilad** [comment]
This is a duplicate of #26. I'll be happy to accept a PR fixing this, and hopefully we can maintain backwards compat (but if not - that's not so bad either)

**Comment by pgilad** [comment]
Hopefully fixed with https://github.com/pgilad/grunt-dev-update/commit/3d0e747929dcf2e303f28a71756a90c19c9d7342

**Comment by diggy** [comment]
seems fixed, thanks! 👍

**Comment by pgilad** [comment]
No problem!
